server: 
  port: 8080
  
spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.9.51:1521:orcl
    username: test
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource